parameters:
    krtv.twig.gedmo_softdeleteable.class: Krtv\Bundle\TwigSoftdeleteableBundle\Twig\Extension\TwigSoftdeleteableExtension
    krtv.twig.gedmo_softdeleteable.entity_manager: doctrine.orm.entity_manager

services:
    krtv.twig.gedmo_softdeleteable:
      class: %krtv.twig.gedmo_softdeleteable.class%
      arguments: ~ # Passed in compiler
      tags:
        - { name: twig.extension }